# Python Operators

In [4]:
x=3
x += 3
x

6

In [6]:
#This is same as
x=3
x=x+3
x

6

In [7]:
x=3
x /= 3
x

1.0

In [8]:
x=3
x **= 3
x

27

In [9]:
x=3
x //= 3
x

1

In [13]:
x=3
y=4
print(x is y)

False


In [14]:
print(x is not y)

True


In [16]:
x=[1,2,3,4]
y=[1,4,5,7]
print(x[0] in y)

True


In [17]:
print(x[0] not in y)

False


In [18]:
print(1 < 5 and 2 >1)

True


In [19]:
print(1 ==0 or 1==-1)

False


In [20]:
print(not(1==1))

False


# Python Comments

In [1]:
# SwiftLearn IT Python Tutorials
#Commenting out a code 
print("Hello World")

Hello World


# Python Variables 

In [2]:
a=1
b=2
c=3
d=a**b/c
print(d)

0.3333333333333333


In [4]:
2b=3   # Wrong label 
print(2b)  

SyntaxError: invalid syntax (<ipython-input-4-b61b711dfc69>, line 1)

# Python Numbers  and Casting 

In [5]:
#Use type method to print the data type
x=3.3
print(type(x))

<class 'float'>


In [6]:
# Converts float to integer
y=3.2
print(int(y))

3


In [7]:
print(complex(y))

(3.2+0j)


# Import Math Library

In [8]:
from math import *

In [9]:
print(round(2.2))

2


In [10]:
print(log(100))

4.605170185988092


In [11]:
print(ceil(4.56787))

5


# Strings

In [18]:
a="I am coming"
print(a)

I am coming


In [23]:
# This returned blank because the second character is "space"
print(a[1])

In [24]:
#Extract the first four characters
b=a[0:4]
print(b)

I am


In [25]:
c= ''' Data and related technologies are the other 
names of SwiftLearn IT Solutions. At SwiftLearn IT, 
we identify technology potentials; groom and make 
them leaders in the technology world.'''
print(c[50:-1])

s of SwiftLearn IT Solutions. At SwiftLearn IT, 
we identify technology potentials; groom and make 
them leaders in the technology world


In [26]:
print(c[-30:])

aders in the technology world.


In [28]:
name="John"
lname="Doe"
print(name + " " + lname)

John Doe


# Some Methods for strings

In [32]:

print(name.upper())
print(name.lower())
print(name[2:3])
print(lname.isupper())

JOHN
john
h
False


# Lists

In [33]:
cars=["Tesla","Benz","Hyundai"]
cars[0]

'Tesla'

# Use FOR and IN 

In [34]:
for i in cars:
    print(i)

Tesla
Benz
Hyundai


In [35]:
for i in range(len(cars)):
    print(i)

0
1
2


# List methods()

In [43]:
billionaires=["Mark","Elon","Buffet","Jack","Dangote"]
billionaires.append("Jeff")  # Appends item to the list

In [44]:
billionaires

['Mark', 'Elon', 'Buffet', 'Jack', 'Dangote', 'Jeff']

In [45]:
billionaires.pop() # Removes last item

'Jeff'

In [46]:
billionaires

['Mark', 'Elon', 'Buffet', 'Jack', 'Dangote']

In [50]:
billionaires.insert(3,"Sultan") #Inserts sultan in the 3rd index
billionaires

['Mark', 'Elon', 'Buffet', 'Sultan', 'Sultan', 'Jack', 'Dangote']

In [53]:
print(billionaires.index("Dangote"))  # Returns the index of an item 

6


# List Comprehension

In [55]:
# Iterating through a loop
nums=[]
for i in range(1,20):
    nums.append(i)
print(nums)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


# Using a List Comprehension for the Same thing

In [57]:
numbers=[i for i in range(1,20)]
numbers

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [59]:
#Extracting letters from word using LC
letters=[i for i in "a e i o u" if i != "a"]
letters

[' ', 'e', ' ', 'i', ' ', 'o', ' ', 'u']

# Tuples

In [5]:
tup1=(1,2,3,4,5)
tup2=("ama","tesla")
print(tup1 + tup2)

(1, 2, 3, 4, 5, 'ama', 'tesla')


In [6]:
#Delete Tuple
del tup1;
print(tup1)

NameError: name 'tup1' is not defined

In [26]:
# index Tuple
tup2.count(1)

0

In [13]:
tup2.index("ama")

0

In [20]:
a=list(tup2)  # Convert tuple to list
a

['ama', 'tesla']

In [24]:
c=("you ") * 5
print(c)

you you you you you 


In [25]:
# Slice tuple
tup2[0]

'ama'

# Tuple Unpacking

In [52]:
a,b,c=(1,2,3)  
print(a, b ,c)

1 2 3


In [53]:
a = ("California", 'MARYLAND', "Chicago")  #Packing of values
(state1, state2,state3) = a  
print(state1)
print(state2)
print(state3)

California
MARYLAND
Chicago


In [54]:
# a takes first item, c last and *b takes the rest
listt=tuple([i for i in range(10)])
a,*b,c=listt 

In [55]:
print(b)

[1, 2, 3, 4, 5, 6, 7, 8]


In [56]:
print(a)
print(c)

0
9


In [57]:
#b,c,d get assigned to last 3 items and * a takes the rest
*a,b,c,d=listt
print(b)
print(c)
print(d)
print(tuple(a))

7
8
9
(0, 1, 2, 3, 4, 5, 6)


# Python Sets

In [1]:
sets={1,2,(1,2,3),"set"}
print(sets)

{'set', 1, 2, (1, 2, 3)}


In [2]:
set=set([i for i in range(5)])
print(set)

{0, 1, 2, 3, 4}


In [3]:
sets.union(set)  #Union

{(1, 2, 3), 0, 1, 2, 3, 4, 'set'}

In [4]:
sets.intersection(set) #intersection

{1, 2}

In [5]:
sets.pop()

'set'

In [6]:
sets.add("name")  # Add only an element
sets

{(1, 2, 3), 1, 2, 'name'}

In [7]:
sets.update(["USA", "Canada","London"]) # Add multiple elements
sets

{(1, 2, 3), 1, 2, 'Canada', 'London', 'USA', 'name'}

# Python Dictionaries

In [2]:
Dict={"name":"owen","age":27,"gender":"male","height":"5.8cm", "color":'black',"status":"citizen"}
print(Dict)

{'name': 'owen', 'age': 27, 'gender': 'male', 'height': '5.8cm', 'color': 'black', 'status': 'citizen'}


In [4]:
# Dictionary with mixed keys
dict={"Name":"Alex","sales":[100,200,400,500,600]}
print(dict)

{'Name': 'Alex', 'sales': [100, 200, 400, 500, 600]}


# Nested Dictionaries

In [6]:
nested={"name":"owen","age":27,"playlist":{"genre1":"rnb","genre2":"gospel","genre3":"reggae"}}
print(nested)

{'name': 'owen', 'age': 27, 'playlist': {'genre1': 'rnb', 'genre2': 'gospel', 'genre3': 'reggae'}}


# Accessing Elements and Dictionary Methods

In [7]:
print(Dict.keys())  # Print all keys in a Dictionary

dict_keys(['name', 'age', 'gender', 'height', 'color', 'status'])


In [8]:
print(nested.values()) #printall values in a dictionary

dict_values(['owen', 27, {'genre1': 'rnb', 'genre2': 'gospel', 'genre3': 'reggae'}])


In [9]:
print(nested["name"])  #prints related value associated with a key

owen


In [10]:
print(nested.get("playlist"))  #  You can also use get access the values

{'genre1': 'rnb', 'genre2': 'gospel', 'genre3': 'reggae'}


In [14]:
print(nested.items())

dict_items([('name', 'owen'), ('age', 27), ('playlist', {'genre1': 'rnb', 'genre2': 'gospel', 'genre3': 'reggae'})])


In [11]:
for keys, values in nested.items():
    print(keys)
    print(values)

name
owen
age
27
playlist
{'genre1': 'rnb', 'genre2': 'gospel', 'genre3': 'reggae'}


In [13]:
#Grab the value of genre1 from the nested dictionary
nested.get("playlist")["genre1"]

'rnb'

In [16]:
nested_copy=nested.copy()  # Clones a dictionary
print(nested_copy)

{'name': 'owen', 'age': 27, 'playlist': {'genre1': 'rnb', 'genre2': 'gospel', 'genre3': 'reggae'}}


# Dictionary Comprehension

In [28]:
Dict={"name":"owen","age":27,"gender":"male",\
      "height":"5.8cm", "color":'black',\
      "status":"citizen"}
for i in Dict:
    print(Dict[i])

owen
27
male
5.8cm
black
citizen


In [29]:
DC={Dict[i] for i in Dict }
DC

{27, '5.8cm', 'black', 'citizen', 'male', 'owen'}

In [30]:
dict2={i:i**2 for i in range(4)}
dict2

{0: 0, 1: 1, 2: 4, 3: 9}

# Python Boolean

In [10]:
print(10==9)

False


In [12]:
print(10<15)

True


In [14]:
print(1 in [1,2,3,4])

True


In [15]:
print(2!=4)

True


In [18]:
print(bool(123))
print(bool({1:1,2:4}))

True
True


# Python Functions
* In built functions

In [21]:
print("Hello world")

Hello world


In [22]:
print(print.__doc__)

print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.


In [23]:
a=[1,2,3,4]
print(len(a))

4


# User Defined Functions

In [28]:
def even(nums):
    """ Check if a number is an even number """
    if nums//2==0:
        print("It is even number ")
    else:
        print("odd number")

In [29]:
even(10)

odd number


In [30]:
print(even.__doc__)  # Printing function doc

 Check if a number is an even number 


# Lambda Functions

In [35]:
a=lambda num:num**3   

In [36]:
a(2)

8

In [37]:
# Same function using UDF
def exp(num):
    return num**3

In [38]:
exp(2)

8

In [39]:
a=lambda x,y,z,a: a+y-z*a

In [40]:
print(a(2,4,6,8))

-36


# Lamba with filter()

In [47]:
a=[i for i in range(20)]
b= filter(lambda i: i%2==1,a)

In [48]:
list(b)

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]

In [50]:
tuple(b)  # This is because it takes list as argument

()

In [54]:
list2=[i for i in range(2,50,3)]
even=filter(lambda num: num%2==1,list2)


In [55]:
list(even)

[5, 11, 17, 23, 29, 35, 41, 47]

# Lamba with map()

In [56]:
a=[i for i in range(3,18,1)]  #Square each element in the list
newlist=map(lambda i : i ** 2,a)

In [57]:
list(newlist)

[9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289]

In [62]:
b=[ i for i in range(30) if i%2==1] # Add 2 to every odd number 
odd=map(lambda x: x+2,b)

In [63]:
list(odd)

[3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31]

# Lambda with reduce()

In [65]:
from functools import reduce
d=[1,2,3,4,5,6,7,8,8,9]  # Sum all elements in the list
sum=reduce(lambda a,b:a+b,d)
sum


53

# While and For loops


In [71]:
for i in range(3,7):
    print(i)

3
4
5
6


In [78]:
x=0   # Index or counter variable
while x<4:
    print(x)
    x+=1  #A set of new operation to excecute till all condition is exhausted.

0
1
2
3


In [79]:
games=["soccer","hockey","basketball","chess"]
for i in games:
    print(i)
    if i=="basketball":
        break

soccer
hockey
basketball


In [83]:
games=["soccer","hockey","basketball","chess"]
for i in games:
    if i=="basketball":
        continue
    print(i)

soccer
hockey
chess


In [86]:
i=0
while i <=10:
    print(i)
    i+=1
    if i%2==0:
        break

0
1


In [90]:
i=0
while i <=2:
    print(i)
    i+=1
    if i%2==0:
        continue
    print(i)

0
1
1
2
3


# If , elif,else Statements

In [100]:
cost=10
if cost < 25:
    print("cost is low")
elif cost > 25 and cost < 29:
    print("cost is medium")
else:
    print("high cost")
    

cost is low


# File Handling-- Read

In [109]:
# Reading File
file=open("C:/Users/User/Desktop/Swiftlearnit codes/file.txt","r")
for line in file:
    print(line)

Python reads,write and append files  with each line terminated with a special character.

Python uses the open() function to handles files in read and write mode.

Handling files in python takes on two arguments i.e. file name and the mode.



In [111]:
#Alternatively
file=open("C:/Users/User/Desktop/Swiftlearnit codes/file.txt","r")
print(file.read())

Python reads,write and append files  with each line terminated with a special character.
Python uses the open() function to handles files in read and write mode.
Handling files in python takes on two arguments i.e. file name and the mode.



In [114]:
# Read first few characters
file=open("C:/Users/User/Desktop/Swiftlearnit codes/file.txt","r")
print(file.read(100))

Python reads,write and append files  with each line terminated with a special character.
Python uses


# File Handling -- Write()

In [127]:
file=open("C:/Users/User/Desktop/Swiftlearnit codes/file.txt","w")
file.write("I am adding this text to the Original text file \n")
file.write("SwiftlearnIT is the place to be \n")
file.write("Perfection is our HallMark")
file.write("""Python reads,write and append files \n
Handling files in python takes on two arguments i.e.""")
file.close()

In [128]:
file=open("C:/Users/User/Desktop/Swiftlearnit codes/file.txt","r")
for line in file:
    print(line)

I am adding this text to the Original text file 

SwiftlearnIT is the place to be 

Perfection is our HallMarkPython reads,write and append files 



Handling files in python takes on two arguments i.e.


# File Handling--append()

In [140]:
file=open("C:/Users/User/Desktop/Swiftlearnit codes/file.txt","a")
file.write(" \n Append this line")
file.close()


In [141]:
file=open("C:/Users/User/Desktop/Swiftlearnit codes/file.txt","r")
for line in file:
    print(line)

I am adding this text to the Original text file 

SwiftlearnIT is the place to be 

Perfection is our HallMarkPython reads,write and append files 



Handling files in python takes on two arguments 

 

 Append this line


# Numpy

In [1]:
import numpy as np

In [2]:
a=[i for i in range(20)]

In [4]:
array=np.array(a)  #One dimensional array
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [5]:
type(array)  # Datatype is array

numpy.ndarray

In [7]:
array.dtype  #Checking datatype of array elements

dtype('int32')

In [9]:
len(array)

20

# Reshaping Array into 2 Dimension

In [12]:
two_dim=array.reshape(4,5) #Produces an array of 4* 5 (matrix)
two_dim   #Double square breackets indicate 2 dimension

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

# Mathematical operations in Numpy

In [14]:
nparray1=np.array([[1,2],[2,3],[4,5]])
nparray2=np.array([[2,3],[5,9],[10,11]])

In [15]:
nparray1

array([[1, 2],
       [2, 3],
       [4, 5]])

In [16]:
nparray2

array([[ 2,  3],
       [ 5,  9],
       [10, 11]])

In [19]:
#Add two arrays
add=np.add(nparray1,nparray2)
add

array([[ 3,  5],
       [ 7, 12],
       [14, 16]])

In [20]:
log=np.log(add)  # Find the log
log

array([[1.09861229, 1.60943791],
       [1.94591015, 2.48490665],
       [2.63905733, 2.77258872]])

In [22]:
sqrt=np.sqrt(add)
sqrt

array([[1.73205081, 2.23606798],
       [2.64575131, 3.46410162],
       [3.74165739, 4.        ]])

# Slicing Array

In [23]:
a 

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [24]:
a[0:5]  # Grab first five elements

[0, 1, 2, 3, 4]

In [26]:
log

array([[1.09861229, 1.60943791],
       [1.94591015, 2.48490665],
       [2.63905733, 2.77258872]])

In [27]:
log[0,1] #grab element from first row and second column

1.6094379124341003

In [28]:
log[2,0:]  #Grab element from third row  and everything from the column

array([2.63905733, 2.77258872])

# Pandas Series

In [32]:
#Create series from list. A series has an index 
import pandas as pd
dat=pd.Series([i for i in range(4)], index=["a","b","c","d"])
dat

a    0
b    1
c    2
d    3
dtype: int64

# Slicing Series

In [33]:
dat["a"]  # Remember we slice by index

0

In [34]:
#Remember in Series we can noncontiguous or nonsequntial indices
dat2=pd.Series([0.5,2.30,0.76,1],index=["america","ghana",\
                                        "nigeria","congo"])
dat2

america    0.50
ghana      2.30
nigeria    0.76
congo      1.00
dtype: float64

In [36]:
dat2[["ghana","congo"]]

ghana    2.3
congo    1.0
dtype: float64

# Series from Dicionary

In [37]:
#Index can be set explicitly
d=pd.Series({2:"A",3:"B",4:"C"},index=[2,4])
d

2    A
4    C
dtype: object

In [41]:

population_dict = {'California': 38332521,\
 'Texas': 26448193,\
 'New York': 19651127,\
 'Florida': 19552860,\
 'Illinois': 12882135}
population = pd.Series(population_dict)
population


California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [42]:
population[["Texas","Florida"]]

Texas      26448193
Florida    19552860
dtype: int64

In [43]:
population[1:3]

Texas       26448193
New York    19651127
dtype: int64

In [2]:
import pandas as pd

# Series from Excel File

In [30]:
pokemon = pd.read_csv("C:/Users/User/Desktop/Data/fortune1000.csv"\
                      ,usecols=["Company","Sector"])
pokemon.head(3) #Print first 3 rows

Company      Sector
0      Walmart   Retailing
1  Exxon Mobil      Energy
2        Apple  Technology

In [31]:
type(pokemon)

pandas.core.frame.DataFrame

In [32]:
series=pokemon["Sector"]

In [33]:
series.head()

0      Retailing
1         Energy
2     Technology
3     Financials
4    Health Care
Name: Sector, dtype: object

In [23]:
type(series)

pandas.core.series.Series

In [24]:
series2=pokemon["Sector"].values

In [11]:
type(series)

pandas.core.series.Series

# Connect to SQL Server

In [40]:
import pyodbc as py
import pandas as pd
#connecting to sql server
conn=py.connect("Driver={SQL Server};"
                "Server=DESKTOP-24K91PB;"  # Specify your servername
                "Database=Northwind;"      #specify the database
                "Trusted_Connection=yes;"  # Ensure a trusted connection
               )

#Insert Query
query="""
        select  top 5 * from dbo.employees
        """

data=pd.read_sql(query,conn)
data.head(2)

EmployeeID LastName FirstName                  Title TitleOfCourtesy  \
0           1  Davolio     Nancy   Sales Representative             Ms.   
1           2   Fuller    Andrew  Vice President, Sales             Dr.   

   BirthDate   HireDate                        Address     City Region  \
0 1948-12-08 1992-05-01  507 - 20th Ave. E.\r\nApt. 2A  Seattle     WA   
1 1952-02-19 1992-08-14             908 W. Capital Way   Tacoma     WA   

  PostalCode Country       HomePhone Extension  \
0      98122     USA  (206) 555-9857      5467   
1      98401     USA  (206) 555-9482      3457   

                                               Photo  \
0  b'\x15\x1c/\x00\x02\x00\x00\x00\r\x00\x0e\x00\...   
1  b'\x15\x1c/\x00\x02\x00\x00\x00\r\x00\x0e\x00\...   

                                               Notes  ReportsTo  \
0  Education includes a BA in psychology from Col...        2.0   
1  Andrew received his BTS commercial in 1974 and...        NaN   

                              PhotoPath  
0  http://accweb/emmployees/davolio.bmp  
1   http://accweb/emmployees/fuller.bmp

# Read JSON

In [42]:
json = {
  "Duration":{
    "0":60,
    "1":60,
    "2":60,
    "3":45,
    "4":45,
    "5":60
  },
  "Pulse":{
    "0":110,
    "1":117,
    "2":103,
    "3":109,
    "4":117,
    "5":102
  }
    
}

In [45]:
#Read JSON
data=pd.DataFrame(json)
data

Duration  Pulse
0        60    110
1        60    117
2        60    103
3        45    109
4        45    117
5        60    102

# Read HTML


In [52]:
url2='http://en.wikipedia.org/wiki/Provinces_and_territories_of_Canada'
data=pd.read_html(url2)

In [53]:
data[0]

Provinces and territories of Canada Provinces and territories of Canada.1
0                                 NaN                                   NaN
1                            Category                       Federated state
2                              Number             10 provinces3 territories

# Pandas DataFrame

In [60]:
pokemon = pd.read_csv("C:/Users/User/Desktop/Data/fortune1000.csv" ,\
                   usecols=["Company","Sector","Revenue"])
pokemon.head(2) # top 2

Company     Sector  Revenue
0      Walmart  Retailing   482130
1  Exxon Mobil     Energy   246204

In [62]:
pokemon.tail(2)  # bottom 2

Company                        Sector  Revenue
998            Wendy’s  Hotels, Resturants & Leisure     1896
999  Briggs & Stratton                   Industrials     1895

# Select Columns

In [29]:
pokemon = pd.read_csv("C:/Users/User/Desktop/Data/fortune1000.csv" )
pokemon.head(2) # top 2

Rank      Company     Sector               Industry         Location  \
0     1      Walmart  Retailing  General Merchandisers  Bentonville, AR   
1     2  Exxon Mobil     Energy     Petroleum Refining       Irving, TX   

   Revenue  Profits  Employees  
0   482130    14694    2300000  
1   246204    16150      75600

In [31]:
# Select Company column
pokemon.Company.head(2)

0        Walmart
1    Exxon Mobil
Name: Company, dtype: object

In [32]:
#Alternatively
pokemon["Company"].head(2)

0        Walmart
1    Exxon Mobil
Name: Company, dtype: object

# Select Multiple Columns

In [35]:
pokemon[["Company","Sector","Revenue"]].head(2)

Company     Sector  Revenue
0      Walmart  Retailing   482130
1  Exxon Mobil     Energy   246204

# Multiply all Revenue by 2
# using lambda function and Apply()

In [75]:
pokemon = pd.read_csv("C:/Users/User/Desktop/Data/fortune1000.csv" ,\
                   usecols=["Company","Sector","Revenue"])
pokemon.head(2) # top 2

Company     Sector  Revenue
0      Walmart  Retailing   482130
1  Exxon Mobil     Energy   246204

In [76]:
def rev(num):
    return num*2

In [77]:
pokemon["New_Revenue"]=pokemon["Revenue"].apply(rev)

In [78]:
pokemon.head(2)

Company     Sector  Revenue  New_Revenue
0      Walmart  Retailing   482130       964260
1  Exxon Mobil     Energy   246204       492408

In [79]:
#Use Lambda Functions with apply
pokemon["New_Rev"]=pokemon["Revenue"].apply(lambda a:a*2)

In [80]:
pokemon.head(2)

Company     Sector  Revenue  New_Revenue  New_Rev
0      Walmart  Retailing   482130       964260   964260
1  Exxon Mobil     Energy   246204       492408   492408

In [81]:
pokemon.columns

Index(['Company', 'Sector', 'Revenue', 'New_Revenue', 'New_Rev'], dtype='object')

# Renaming Columns

In [3]:
pokemon = pd.read_csv("C:/Users/User/Desktop/Data/fortune1000.csv" )
pokemon.head(2) # top 2

Rank      Company     Sector               Industry         Location  \
0     1      Walmart  Retailing  General Merchandisers  Bentonville, AR   
1     2  Exxon Mobil     Energy     Petroleum Refining       Irving, TX   

   Revenue  Profits  Employees  
0   482130    14694    2300000  
1   246204    16150      75600

In [4]:
pokemon.columns

Index(['Rank', 'Company', 'Sector', 'Industry', 'Location', 'Revenue',
       'Profits', 'Employees'],
      dtype='object')

# Using .columns variable assigment

In [6]:

pokemon.columns=["Rnk","Comp","Sect","Ind","Loc","Rev","Profit","Emp"]
pokemon.head(2)

Rnk         Comp       Sect                    Ind              Loc  \
0    1      Walmart  Retailing  General Merchandisers  Bentonville, AR   
1    2  Exxon Mobil     Energy     Petroleum Refining       Irving, TX   

      Rev  Profit      Emp  
0  482130   14694  2300000  
1  246204   16150    75600

# Use Rename()

In [9]:
pokemon.rename(columns={"Rnk":"Rnk2","Comp":"Comp2","Sect":"Sect2"},inplace=True)
pokemon.head(2)

Rnk2        Comp2      Sect2                    Ind              Loc  \
0     1      Walmart  Retailing  General Merchandisers  Bentonville, AR   
1     2  Exxon Mobil     Energy     Petroleum Refining       Irving, TX   

      Rev  Profit      Emp  
0  482130   14694  2300000  
1  246204   16150    75600

# Drop Columns and Rows

In [17]:
pokemon = pd.read_csv("C:/Users/User/Desktop/Data/fortune1000.csv" )
pokemon.head(2) # top 2

Rank      Company     Sector               Industry         Location  \
0     1      Walmart  Retailing  General Merchandisers  Bentonville, AR   
1     2  Exxon Mobil     Energy     Petroleum Refining       Irving, TX   

   Revenue  Profits  Employees  
0   482130    14694    2300000  
1   246204    16150      75600

In [18]:
#Drop Columns
df=pokemon.drop(columns=["Industry","Location","Sector"],axis=1)
df.head(2)

Rank      Company  Revenue  Profits  Employees
0     1      Walmart   482130    14694    2300000
1     2  Exxon Mobil   246204    16150      75600

In [20]:
#Drop Rows without inpllace
pokemon.drop([0,2], axis=0, inplace=False)
pokemon.head(2)

Rank      Company     Sector               Industry         Location  \
0     1      Walmart  Retailing  General Merchandisers  Bentonville, AR   
1     2  Exxon Mobil     Energy     Petroleum Refining       Irving, TX   

   Revenue  Profits  Employees  
0   482130    14694    2300000  
1   246204    16150      75600

In [21]:
#Drop Rows with inplace
pokemon.drop([0,2], axis=0, inplace=True)
pokemon.head(2)

Rank             Company      Sector  \
1     2         Exxon Mobil      Energy   
3     4  Berkshire Hathaway  Financials   

                                   Industry    Location  Revenue  Profits  \
1                        Petroleum Refining  Irving, TX   246204    16150   
3  Insurance: Property and Casualty (Stock)   Omaha, NE   210821    24083   

   Employees  
1      75600  
3     331000

# Sort Columns

In [22]:
pokemon = pd.read_csv("C:/Users/User/Desktop/Data/fortune1000.csv" )
pokemon.head(2) # top 2

Rank      Company     Sector               Industry         Location  \
0     1      Walmart  Retailing  General Merchandisers  Bentonville, AR   
1     2  Exxon Mobil     Energy     Petroleum Refining       Irving, TX   

   Revenue  Profits  Employees  
0   482130    14694    2300000  
1   246204    16150      75600

In [23]:
pokemon["Revenue"].sort_values(ascending=True).head(2) # Asecending order

999    1895
998    1896
Name: Revenue, dtype: int64

In [24]:
pokemon["Revenue"].sort_values(ascending=False).head(2) # Descending Order

0    482130
1    246204
Name: Revenue, dtype: int64

# Sort Dataframes

In [28]:
pokemon.sort_values(["Revenue"],ascending=False).head(2)

Rank      Company     Sector               Industry         Location  \
0     1      Walmart  Retailing  General Merchandisers  Bentonville, AR   
1     2  Exxon Mobil     Energy     Petroleum Refining       Irving, TX   

   Revenue  Profits  Employees  
0   482130    14694    2300000  
1   246204    16150      75600

# Filter Rows

In [36]:
pokemon = pd.read_csv("C:/Users/User/Desktop/Data/fortune1000.csv" )
pokemon.head(2) # top 2

Rank      Company     Sector               Industry         Location  \
0     1      Walmart  Retailing  General Merchandisers  Bentonville, AR   
1     2  Exxon Mobil     Energy     Petroleum Refining       Irving, TX   

   Revenue  Profits  Employees  
0   482130    14694    2300000  
1   246204    16150      75600

### Select All Rows with Revenue greater than 100,000

In [39]:
pokemon[pokemon.Revenue > 100000].head(2)

Rank      Company     Sector               Industry         Location  \
0     1      Walmart  Retailing  General Merchandisers  Bentonville, AR   
1     2  Exxon Mobil     Energy     Petroleum Refining       Irving, TX   

   Revenue  Profits  Employees  
0   482130    14694    2300000  
1   246204    16150      75600

In [42]:
#Alternatively
pokemon[pokemon["Revenue"] > 100000].head(2)

Rank      Company     Sector               Industry         Location  \
0     1      Walmart  Retailing  General Merchandisers  Bentonville, AR   
1     2  Exxon Mobil     Energy     Petroleum Refining       Irving, TX   

   Revenue  Profits  Employees  
0   482130    14694    2300000  
1   246204    16150      75600

### Select All  Revenue between 100000 and 120000

In [46]:
greater1=pokemon["Revenue"] >= 100000
less1=pokemon["Revenue"] <=120000
pokemon[(greater1) & (less1)].head(2)

Rank     Company      Sector                    Industry        Location  \
14    15      Costco   Retailing  Specialty Retailers: Other    Issaquah, WA   
15    16  Fannie Mae  Financials      Diversified Financials  Washington, DC   

    Revenue  Profits  Employees  
14   116199     2377     161000  
15   110359    10954       7300

In [50]:
# Alrernatively. Treat each filtering clause independently
pokemon[(pokemon["Revenue"] >=100000) & (pokemon["Revenue"] <=120000)].head(2)

Rank     Company      Sector                    Industry        Location  \
14    15      Costco   Retailing  Specialty Retailers: Other    Issaquah, WA   
15    16  Fannie Mae  Financials      Diversified Financials  Washington, DC   

    Revenue  Profits  Employees  
14   116199     2377     161000  
15   110359    10954       7300

# Distinct Values

In [ ]:
# Give count of all unique attributes under sector
pokemon["Sector"].value_counts()

In [52]:
# Print the Unique attributes for sector
pokemon["Sector"].unique()

array(['Retailing', 'Energy', 'Technology', 'Financials', 'Health Care',
       'Food and Drug Stores', 'Motor Vehicles & Parts',
       'Telecommunications', 'Industrials', 'Aerospace & Defense',
       'Household Products', 'Food, Beverages & Tobacco',
       'Transportation', 'Media', 'Chemicals', 'Wholesalers', 'Apparel',
       'Hotels, Resturants & Leisure', 'Materials', 'Business Services',
       'Engineering & Construction'], dtype=object)

In [55]:
# Count the unique attributes for sector
pokemon["Sector"].nunique()

21

### Filtering Categorical or Dimension Attributes

In [57]:
# Filter all rows where sector is
#Retailinng,Energy and Technology
a=pokemon['Sector']=="Retailing"
b=pokemon['Sector']=="Energy"
c=pokemon['Sector']=="Technology"
pokemon[(a)|(b)|(c)].head(2)

Rank      Company     Sector               Industry         Location  \
0     1      Walmart  Retailing  General Merchandisers  Bentonville, AR   
1     2  Exxon Mobil     Energy     Petroleum Refining       Irving, TX   

   Revenue  Profits  Employees  
0   482130    14694    2300000  
1   246204    16150      75600

In [64]:
#Alternatively
pokemon[(pokemon['Sector']=="Retailing") |\
        (pokemon['Sector']=="Energy") |\
        (pokemon['Sector']=="Technology")].head(2)

Rank      Company     Sector               Industry         Location  \
0     1      Walmart  Retailing  General Merchandisers  Bentonville, AR   
1     2  Exxon Mobil     Energy     Petroleum Refining       Irving, TX   

   Revenue  Profits  Employees  
0   482130    14694    2300000  
1   246204    16150      75600

### Use isin()

In [67]:
list=['Retailing', 'Energy', 'Technology']
pokemon[pokemon["Sector"].isin(list)].head(2)

Rank      Company     Sector               Industry         Location  \
0     1      Walmart  Retailing  General Merchandisers  Bentonville, AR   
1     2  Exxon Mobil     Energy     Petroleum Refining       Irving, TX   

   Revenue  Profits  Employees  
0   482130    14694    2300000  
1   246204    16150      75600

# String Handling


In [70]:
#Convert columnnames to Upper cases
pokemon.columns=pokemon.columns.str.upper()

In [71]:
pokemon.head(2)

RANK      COMPANY     SECTOR               INDUSTRY         LOCATION  \
0     1      Walmart  Retailing  General Merchandisers  Bentonville, AR   
1     2  Exxon Mobil     Energy     Petroleum Refining       Irving, TX   

   REVENUE  PROFITS  EMPLOYEES  
0   482130    14694    2300000  
1   246204    16150      75600

# Contains

In [73]:
#Produce all records with company attribute that contains"art"
pokemon[pokemon["COMPANY"].str.contains("mart")].head(2)

RANK               COMPANY                SECTOR               INDUSTRY  \
0       1               Walmart             Retailing  General Merchandisers   
594   595  Smart & Final Stores  Food and Drug Stores   Food and Drug Stores   

            LOCATION  REVENUE  PROFITS  EMPLOYEES  
0    Bentonville, AR   482130    14694    2300000  
594     Commerce, CA     3971       38       6939

# Check and Change DataType

In [77]:
pokemon = pd.read_csv("C:/Users/User/Desktop/Data/fortune1000.csv" )
pokemon.head(2) # top 2

Rank      Company     Sector               Industry         Location  \
0     1      Walmart  Retailing  General Merchandisers  Bentonville, AR   
1     2  Exxon Mobil     Energy     Petroleum Refining       Irving, TX   

   Revenue  Profits  Employees  
0   482130    14694    2300000  
1   246204    16150      75600

In [78]:
pokemon.dtypes

Rank          int64
Company      object
Sector       object
Industry     object
Location     object
Revenue       int64
Profits       int64
Employees     int64
dtype: object

### Change Revenue to float

In [80]:
pokemon["Revenue"]=pokemon["Revenue"].astype(float)
pokemon.dtypes

Rank           int64
Company       object
Sector        object
Industry      object
Location      object
Revenue      float64
Profits        int64
Employees      int64
dtype: object

In [83]:
pokemon = pd.read_csv("C:/Users/User/Desktop/Data/fortune1000.csv",dtype={"Rank":float} )
pokemon.dtypes.head(2)

Rank       float64
Company     object
dtype: object

# Group By

In [84]:
pokemon = pd.read_csv("C:/Users/User/Desktop/Data/fortune1000.csv")
pokemon.head(2) # top 2

Rank      Company     Sector               Industry         Location  \
0     1      Walmart  Retailing  General Merchandisers  Bentonville, AR   
1     2  Exxon Mobil     Energy     Petroleum Refining       Irving, TX   

   Revenue  Profits  Employees  
0   482130    14694    2300000  
1   246204    16150      75600

### Groupby Industry and find sum of employees

In [87]:
pokemon.groupby("Industry").sum()["Employees"].head(2)

Industry
Advertising, marketing    124100
Aerospace and Defense     968057
Name: Employees, dtype: int64

### Use .Agg()

In [89]:
pokemon.groupby("Industry").agg(["sum","mean","count"]).head(2)

Rank              Revenue                Profits  \
                         sum   mean count     sum     mean count     sum   
Industry                                                                   
Advertising, marketing   541  270.5     2   22748  11374.0     2    1549   
Aerospace and Defense   8870  443.5    20  357940  17897.0    20   28742   

                                     Employees                  
                          mean count       sum      mean count  
Industry                                                        
Advertising, marketing   774.5     2    124100  62050.00     2  
Aerospace and Defense   1437.1    20    968057  48402.85    20

# Exploratory Data Analysis

In [90]:
pokemon = pd.read_csv("C:/Users/User/Desktop/Data/fortune1000.csv")
pokemon.head(2) # top 2

Rank      Company     Sector               Industry         Location  \
0     1      Walmart  Retailing  General Merchandisers  Bentonville, AR   
1     2  Exxon Mobil     Energy     Petroleum Refining       Irving, TX   

   Revenue  Profits  Employees  
0   482130    14694    2300000  
1   246204    16150      75600

In [91]:
pokemon.shape  # 1000 rows, 8 columns

(1000, 8)

In [92]:
pokemon.isnull().sum()  # No missing values

Rank         0
Company      0
Sector       0
Industry     0
Location     0
Revenue      0
Profits      0
Employees    0
dtype: int64

In [93]:
pokemon.describe()

Rank        Revenue       Profits     Employees
count  1000.00000    1000.000000   1000.000000  1.000000e+03
mean    500.49600   13535.525000    894.093000  3.302800e+04
std     288.81727   28820.519135   3297.063594  9.042769e+04
min       1.00000    1895.000000 -23119.000000  5.200000e+01
25%     250.75000    2898.250000     82.750000  6.405250e+03
50%     500.50000    5113.000000    282.500000  1.251950e+04
75%     750.25000   11386.000000    784.500000  2.812500e+04
max    1000.00000  482130.000000  53394.000000  2.300000e+06

# Pandas Profiling

In [98]:
# !pip install pandas-profiling 
from pandas_profiling import ProfileReport

In [99]:
#Create profile report
profile=ProfileReport(pokemon,title="Pandas Profiling", explorative=True)

In [100]:
profile.to_widgets()

In [101]:
profile.to_file("profile.html")

# Export Excel 

In [124]:
items = pd.read_table("http://bit.ly/chiporders",encoding = "utf-8")
items.head(3) 

order_id  quantity                     item_name choice_description  \
0         1         1  Chips and Fresh Tomato Salsa                NaN   
1         1         1                          Izze       [Clementine]   
2         1         1              Nantucket Nectar            [Apple]   

  item_price  
0     $2.39   
1     $3.39   
2     $3.39

In [125]:
#Create Excel file and Export Data 
excel_file = pd.ExcelWriter("items_Description.xlsx")
items.to_excel(excel_file, sheet_name = "items", index = False)

In [126]:
excel_file.save()

# Export `DataFrame` to CSV File with the `.to_csv()` Method

In [127]:
items.to_csv("items.csv", index = False)